### ISSUE TITLE
Cannot find an artifact

### ISSUE THREAD

**Issue by aleixpol** [bilelmoussaoui/flatpak-github-actions#10]
I've tried to use your action. It looks very convenient but I fail to see how to get the output. Is there something I'm missing?

https://github.com/aleixpol/maliit-flatpak/actions/runs/188988338
https://github.com/aleixpol/maliit-flatpak/runs/929006125?check_suite_focus=true

https://github.com/aleixpol/maliit-flatpak/blob/master/.github/workflows/flatpak.yml

Thanks in advance!

**Comment by bilelmoussaoui** [comment]
The bundle updating isn't there yet. The action itself is more of an idea for now, I will hopefully find the time to clean it up someday,

You can find various github actions that allows you to upload a bundle and upload your `maliit-keyboard-nightly.flatpak` file.

**Comment by aleixpol** [comment]
I don't understand what it does then.
Can you point me to the ones that work? Also I'd recommend taking it off the marketplace, it's how I ended up here.

**Comment by bilelmoussaoui** [comment]
> I don't understand what it does then.
> Can you point me to the ones that work? Also I'd recommend taking it off the marketplace, it's how I ended up here.

It builds correctly your flatpak, it's just a bit of manual work right now 

I can't find a way to do so, there's a wip branch that should hopefully workaround some of the limitations and make it work. Thought I can't work on that anytime soon.

**Comment by bilelmoussaoui** [comment]
This is usable now, see the readme for details. The artifact can be downloaded by clicking on a successful job's details  https://github.com/bilelmoussaoui/flatpak-github-actions/runs/1284652505
