### ISSUE TITLE
Allow updating a remote with flat-manager

### ISSUE THREAD

**Issue by bilelmoussaoui** [bilelmoussaoui/flatpak-github-actions#16]
we will need to provide a way to set a remote url & a token and use flat-manager to upload the build to the remote.

**Comment by btkostner** [comment]
I'm not sure if you are planning on using node or the official `flat-manager-client` python script, but if it's the second, it might be better to split it off to it's own action. I'd also recommend doing something like `setup-flat-manager-client`. That way people could run what ever commands they needed. Similar to how these projects do it:

https://github.com/actions/setup-node
https://github.com/hashicorp/setup-terraform

**Comment by bilelmoussaoui** [comment]
> I'm not sure if you are planning on using node or the official `flat-manager-client` python script, but if it's the second, it might be better to split it off to it's own action. I'd also recommend doing something like `setup-flat-manager-client`. That way people could run what ever commands they needed. Similar to how these projects do it:
> 
> https://github.com/actions/setup-node
> https://github.com/hashicorp/setup-terraform

I'm not a fan of making things super customizable like the actions above do. flat-manager would be set up on every image we offer to the users (developers) and they should just give us a token & publish url. If both are provided -> we try to publish the bundle, if not that step is ignored.
