### ISSUE TITLE
Allow building AArch64 artifacts

### ISSUE THREAD

**Issue by aleixpol** [bilelmoussaoui/flatpak-github-actions#18]
I've no idea how it works, but it would be great.

**Comment by bilelmoussaoui** [comment]
You just need to specify a proper runner and it should work without any changes from the action's side. Although I have no idea if Github provides such runners for free

**Comment by bilelmoussaoui** [comment]
See https://github.community/t/testing-against-multiple-architectures/17111
Closing as nothing can be done from my side
