### ISSUE TITLE
Provide multiple images per runtimes 

### ISSUE THREAD

**Issue by bilelmoussaoui** [bilelmoussaoui/flatpak-github-actions#20]
For now we only have fdo//20.08 pre-installed. We should provide an image per runtime per version, I think we can hack some CI to automate all of that using Github Actions and publish the images somewhere like Dockerhub

**Comment by nahuelwexd** [comment]
I currently have an action on the Replay's repo to do something like this, but with the GNOME Nightly SDK. It builds the Docker image, and uploads it to Docker Hub. Maybe I can do it for here too

**Comment by bilelmoussaoui** [comment]
Ah do you have something I can look at ? unless you want to give it a try. It should just create multiple images per the number of sdks there's so fdo, gnome, kde and for each of those have a specific tag per version of the sdk we support and have the CI generate all the images and push them to docker hub. We can then schedule the job weekly to ensure they stay up to date

**Comment by nahuelwexd** [comment]
If u confirm that u've not started working on this yet, I'll self-assign the issue and start trying to implement it tomorrow or the day after tomorrow

**Comment by bilelmoussaoui** [comment]
Feel free to look at it, otherwise I will do this weekend
