### ISSUE TITLE
Arch option / cross-compile

### ISSUE THREAD

**Issue by andyholmes** [bilelmoussaoui/flatpak-github-actions#35]
Is it possible to add an option for `arch` so that we can cross-compile for eg. `aarch64`? It would be convenient to have builds churned out for x86_64 and aarch64 for testing on mobile devices.

**Comment by nahuelwexd** [comment]
I find this issue similar to #18 :thinking:

**Comment by andyholmes** [comment]
It does seem similar, I think the close might have been something of a misunderstanding?

Currently I'm cross-compiling as was once described on the freedesktop mailing-list (don't have a link handy). This amounts to something along the lines of:

```
dnf install qemu-system-arm qemu-user-static
flatpak install org.gnome.Sdk/aarch64/40 org.gnome.Platform/aarch64/40

flatpak-builder --arch=aarch64 --repo=repo --force-clean build-dir com.example.App.json
flatpak build-bundle --arch=aarch64 ./repo/ com.example.App.flatpak com.example.App
```

**Comment by bilelmoussaoui** [comment]
The first thing we will need to figure out is how to provide images for arch other than x86_64. Once that part is properly handled we can try adding something based on qemu, but I was just too afraid that it would be super slow.

**Comment by nahuelwexd** [comment]
> The first thing we will need to figure out is how to provide images for arch other than x86_64.

This can be done with qemu, see https://github.com/docker/build-push-action/blob/master/docs/advanced/multi-platform.md

**Comment by andyholmes** [comment]
> The first thing we will need to figure out is how to provide images for arch other than x86_64.

From glancing at the workflow I think you would just add an extra entry for aarch64 each platform. I'm not sure if running whole images via qemu is possible with github actions, but I'm guessing flatpak-builder uses qemu as appropriate if it is available. That's how I do it locally anyways.

> we can try adding something based on qemu, but I was just too afraid that it would be super slow.

I can confirm it is quite slow, at least on my wimpy laptop. I'll shamelessly admit that's part of the reason I'd like this feature :)
