### ISSUE TITLE
Prepare docker image

### ISSUE THREAD

**Issue by bilelmoussaoui** [bilelmoussaoui/flatpak-github-actions#5]
Currently, the wip branch uses `nahuelwexd/flatpak-docker:latest` we should switch to using a docker image based on Dockerfile hosted here on github

cc @nahuelwexd

**Comment by nahuelwexd** [comment]
Hey, we cannot do anything with the "official" flatpak docker images? https://hub.docker.com/r/flatpak/flatpak-builder

**Comment by nahuelwexd** [comment]
Submitted a PR that fixes this, also, there's no need to use GitHub Actions to build the Docker Image. I looked into the Docker Hub options, and there's an option to automatically build images from any repository, and you can specify the dockerimage file and the context, so you can point to the docker-image folder

**Comment by bilelmoussaoui** [comment]
> Hey, we cannot do anything with the "official" flatpak docker images? https://hub.docker.com/r/flatpak/flatpak-builder

There's no official Flatpak docker images. 




> Submitted a PR that fixes this, also, there's no need to use GitHub Actions to build the Docker Image. I looked into the Docker Hub options, and there's an option to automatically build images from any repository, and you can specify the dockerimage file and the context, so you can point to the docker-image folder

Right, thanks! i'm not very familiar with Docker Hub. I will take a look

**Comment by nahuelwexd** [comment]
Reopened until the docker image on Docker Hub is updated
