### ISSUE TITLE
Add suppport for Electron2.BaseApp

### ISSUE THREAD

**Issue by MartinIIOT** [bilelmoussaoui/flatpak-github-actions#58]
Hello,
is it possible to add support for[ Electron2.BaseApp](https://docs.flatpak.org/en/latest/electron.html)?
Or if it's now supported, how to build it with your action?

Thank you.

**Comment by bilelmoussaoui** [comment]
It will be automatically installed before the build starts. The available images that includes a pre installed sdk are provided to reduce the amount of downloads from flathub. You can also have your own ci job to produce such image based on the one provided by our GitHub action

**Comment by bilelmoussaoui** [comment]
any reason why this was re-opened?
