### ISSUE TITLE
CMake FetchContent Fails

### ISSUE THREAD

**Issue by Curve** [bilelmoussaoui/flatpak-github-actions#70]
When using this Action CMake's FetchContent fails with the following message:

```
fatal: unable to access 'https://github.com/TartanLlama/expected/': Could not resolve host: github.com
```

**Comment by bilelmoussaoui** [comment]
Ah, flatpak expects to fetch the dependencies at update dependencies build sage

**Comment by Curve** [comment]
> Ah, flatpak expects to fetch the dependencies at update dependencies build sage 

Ah, thanks, I should be able to fetch the sources before the build and then tell cmake to use the local sources :D

**Comment by bilelmoussaoui** [comment]
That should work, please open issues about anything weird/unexpected you find. The extension have been mostly tested with meson so far

**Comment by bilelmoussaoui** [comment]
Never mind my comment, I thought the issue was on flatpak-vscode and not flatpak-github-actions...
