### ISSUE TITLE
Use run-without-fuse flatpak builder's branch

### ISSUE THREAD

**Issue by nahuelwexd** [bilelmoussaoui/flatpak-github-actions#8]
Flatpak Builder have a branch called run-without-fuse, that is actually being used in GNOME to build the GNOME Runtime Images, used for CI in the GNOME GitLab instance. Actually, we've so much problems trying to use the flatpak-builder build from Fedora, so I think we should use that branch instead.

**Comment by bilelmoussaoui** [comment]
We should switch to use that as well I guess. We will need to have a docker image with it I suppose?

**Comment by bilelmoussaoui** [comment]
Btw, I sent you an invite to have write access to this repository so you can update/merge stuff if I'm not around :D hope you don't mind that!

**Comment by nahuelwexd** [comment]
> We should switch to use that as well I guess. We will need to have a docker image with it I suppose?

Yes... But just adding a few lines to the Dockerfile in order to build the Flatpak Builder should be enough

> Btw, I sent you an invite to have write access to this repository so you can update/merge stuff if I'm not around :D hope you don't mind that!

Wow! I wasn't expecting that. Thx...


PS: I was looking around the GNOME CITemplates and the GNOME Runtime Images... and they seems to be pretty much the same that we're wanting to do here. So... Maybe we can just be a "copy" of that but on GitHub?

**Comment by bilelmoussaoui** [comment]
Yeah that's exactly my plain with this repository, allowing people to test their flatpak manifests easily on Github! it would be very useful for elementary for example and other third party developers

**Comment by nahuelwexd** [comment]
Yes, I also saw the PR open in Akira. So I'll update a few things in entrypoint.sh and the Dockerfile to get closer to the GNOME approach for CI

**Comment by bilelmoussaoui** [comment]
Nice! Let me know if I can help with anything; if you use matrix, feel free to ping me there (@bilelmoussaoui:gnome.org); it should be way easier to discuss than on a Github issue

**Comment by nahuelwexd** [comment]
Well, this was fixed on f14f60fa8e945bd5e33c1a630120de123477ccd6, I forgot to put the "fixes"
